services:
  radio:
    image: gingld/fizteh-radio:latest
    container_name: radio
    restart: always
    ports:
      - 8082:8082
    volumes:
      - /$DB_SQLITE:/radio/storage:rw
      - cache:/radio/.cache
      - manifest:/radio/tmp/man
      - content:/radio/tmp/content
      - tmp_server:/radio/tmp/server
      - ./.log/radio:/radio/.log      
    env_file:
      - .env
    devices:
      - /dev/snd:/dev/snd
    network_mode: host
  proxy:
    build: .nginx/Dockerfile
    container_name: radio-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - /$FRONTEND_FILES:/usr/share/nginx/html:ro
      - manifest:/manifest:ro
      - content:/content:ro
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.log/nginx:/var/log/nginx
      - /$SSL:/etc/ssl:ro
    depends_on:
      - radio
    network_mode: host

volumes:
  cache:
  manifest:
  content:
  tmp_server: