env: local
storage_path: ./storage/storage.sqlite
token_ttl: 1h
http_server:
  address: localhost:8082
  timeout: 4s
  idle_timeout: 60s
  tmp_dir: ./tmp
source_storage:
  path: ./storage
  nesting_depth: 2
  id_length: 4
dash:
  manifest_path: ./tmp/man/man.mpd
  content_dir: ./tmp/content
  chunk_length: 2s
  buffer_time: 30s
  buffer_depth: 5s
  client_update_freq: 10s
  dash_update_freq: 5s
  dash_horizon: 5m