env: prod
log_path: /radio/.log/radio.log
storage_path: /radio/storage/storage.sqlite
token_ttl: 1h
listener_timeout: 5s
http_server:
  address: :8082
  timeout: 4s
  idle_timeout: 60s
  tmp_dir: /radio/tmp/server
source_storage:
  path: ./source
  nesting_depth: 5
  id_length: 8
dash:
  dash_on_start: true
  manifest_path: /radio/tmp/man/man.mpd
  content_dir: /radio/tmp/content
  chunk_length: 2s
  buffer_time: 4s
  buffer_depth: 4s
  client_update_freq: 1s
  dash_update_freq: 1s
  dash_horizon: 10s
dj:
  dj_on_start: true
  cache_file: .cache/dj.json
live:
  delay: 5s
  step_duration: 10s
  source-type: alsa
  source: hw:1,0
  filters:
    pan : stereo|c0<c0+c1|c1<c0+c1
    volume : 20dB