name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [linux/arm64, linux/amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | \
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push ARM64
        id: dockerbuildarm64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: gingld/fizteh-radio:latest
      - name: Build and push x8664
        id: dockerbuildx8664
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: gingld/fizteh-radio:latest
