name: Build App

on:
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to Docker Hub
          run: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | \
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Build Docker image
          run: |
            docker build \
            --platform linux/amd64,linux/arm64,linux/arm/v8 \
            -t radio:latest .
        - name: Push Docker image
          run: |
            docker tag radio:latest gingld/fizteh-radio:latest 
            docker push gingld/fizteh-radio:latest