name: Build App

on:
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to Docker Hub
          run: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | \
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        # - name: Build Docker image
        #   run: |
        #     docker run --privileged --rm tonistiigi/binfmt --install all && \
        #     docker buildx create --name mybuilder --platform linux/amd64,linux/arm64,linux/arm64/v8 && \
        #     docker buildx use mybuilder && \
        #     docker buildx ls && \
        #     docker buildx inspect && \
        #     docker buildx ls && \
        #     docker buildx inspect && \
        #     docker buildx build \
        #     --platform linux/amd64,linux/arm64,linux/arm/v8 \
        #     -t radio:latest .
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/arm64
            push: true
            tags: gingld/fizteh-radio:latest
        # - name: Push Docker image
        #   run: |
        #     docker tag radio:latest gingld/fizteh-radio:latest 
        #     docker push gingld/fizteh-radio:latest